### ISSUE TITLE
General TODO

### ISSUE THREAD

**Issue by NPException42** [NPException42/NPArcade#1]
- [x] sync between client and server who is playing on the arcade right now. (done by linking the seat and the arcade)
- [x] make an abstract game class
- [x] implement a game
- [x] play game on client
- [ ] send screen image to server
  - distribute screen image to clients who are not the player on the arcade
  - do research on how send the images with the lowest possible amount of data.
- [ ] send data in PNG format.
- [ ] make arcade stool take damage when used as weapon
- [ ] make more parts, so you actually need to craft the arcade piece by piece. should be more or less expensive and the parts should be usable on their own. I don't want parts that only exist to make a recipe more complicated...
  - Controller: can be used to act as a wireless controller for the arcade
  - Monitor-Block: can be placed to be a larger screen for the arcade
  - Screen-Connector: can be used to connect the arcade to an external screen
- [ ] make arcade machines dungeonloot
- [ ] take sounds as Wrapper with (String fileHash, File soundFile)
  - store the hash in a list
    - sync the list accross all clients
    - if a client does not have the sound, fetch it from the server
  - register soundfile on clients and server
  - play sound the default way
- [ ] OPTIONAL: some some onVictory() and onGameOver() method in the IArcadeMachine interface, so that some particles could be fired or something...
- [x] send player name to game (leaderboards?)
- [x] count amount of damage on hit to increase possibility of failing
- [ ] sync damage between client and server (custom packets?)
- [ ] fillWithRain(world, x, y, z) -> increase damage if it stands in the rain for too long
- [ ] on high damage:
  - distort picture (white noise, but only apply on clientSide)
  - miss inputs
- [ ] (make it as configurable as possible - render distance and screen receiving distance f.e.)
  - Write a wrapper for Prelude of the Chambered (or make it work somehow at least)
- [ ] make arcade machine use coins (custom item)
- [ ] implement MinecraftForge.setBlockHarvestLevel(Block block, String toolClass, int tier)
  - (see http://www.minecraftforge.net/wiki/Basic_Blocks for reference)
- [ ] new interface: IArcadeServerSideProgram
  - executes the program on the server side
  - (f.e. launching a starbound server from the arcade)
- [ ] IN THE FAR FUTURE: arcade networks, multiplayer -> IMPArcadeGame interface

**Comment by NPException42** [comment]
Will rewrite completely from scratch.
